[tool.poetry]
name = "pelican"
version = "0.6.0"
description = ""
authors = ["CTDS UChicago <cdis@uchicago.edu>"]

[tool.poetry.dependencies]
python = ">=3.6.1,<3.8"
pypfb = "^0.5.7"
fastavro = "^1.3.1"
requests = "^2.25.1"
psycopg2-binary = "^2.8.6"
pyspark = "^3.0.1"
psutil = "^5.8.0"
boto3 = "^1.17.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
